kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: chaincode-pv-volumeclaim
spec:

  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      type: chaincode-pv-volume
      purpose: dev
  resources:
    requests:
      storage: 3Gi
