kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: peer0-pv-claim
spec:

  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      type: org1-pv-volume
      purpose: dev
  resources:
    requests:
      storage: 3Gi
