kind: Deployment
apiVersion: apps/v1
metadata:
  name: cli-pod
spec:
  selector:
    matchLabels:
      app: cli-pod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cli-pod
    spec:

      containers:
      - image: hyperledger/fabric-tools
        name: cli-pod
        imagePullPolicy: Never
        tty: true
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: [ "/bin/bash" ]
        env:
        - name: GOPATH
          value: /opt/gopath
        - name: CORE_PEER_ADDRESS
          value: org1-peer0-svc:8051

        - name: CORE_PEER_ID
          value: cli-pod
        - name: CORE_PEER_LOCALMSPID
          value: Org1MSP

        - name: CORE_PEER_TLS_CERT_FILE
          value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt
        - name: CORE_PEER_TLS_ENABLED
          value: "true"
        - name: CORE_PEER_TLS_KEY_FILE
          value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
        - name: CORE_VM_ENDPOINT
          value: unix:///host/var/run/docker.sock
        - name: FABRIC_LOGGING_SPEC
          value: DEBUG
        - name: CORE_PEER_MSPCONFIGPATH
          value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp

        - name: CORE_PEER_ADDRESSAUTODETECT
          value: "true"
        - name: CORE_PEER_TLS_SERVERHOSTOVERRIDE
          value: peer0.org1.example.com
        - name: CHANNEL_NAME
          value: mychannel

        volumeMounts:
        - name: cli-certificate
          mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - name: channel-artifacts
          mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts/
        - name: chaincode
          mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode/
        - name: docker
          mountPath: /host/var/run/


      volumes:
      - name: cli-certificate
        persistentVolumeClaim:
          claimName: data-crypto-config-volumeclaim
      - name: channel-artifacts
        persistentVolumeClaim:
          claimName: data-channel-artifacts-volumeclaim2
      - name: chaincode
        persistentVolumeClaim:
          claimName: data-chaincode-volumeclaim
      - name: docker
        hostPath:
          path: /var/run
          type: Directory
  

