apiVersion: v1
kind: Service
metadata:
  name: couchdb0-peer0org2
spec:
  ports:
  - port: 5985
    targetPort: 5984
  type: NodePort
  selector:
    app: couchdb0-peer0org2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb0-peer0org2
spec:
  selector:
    matchLabels:
      app: couchdb0-peer0org2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: couchdb0-peer0org2
    spec:

      containers:
      - image: hyperledger/fabric-couchdb
        imagePullPolicy: IfNotPresent
        name: couchdb2
        env:
        - name: COUCHDB_USER
          value: admin
        - name: COUCHDB_PASSWORD
          value: admin
        ports:
        - containerPort: 5984
          name: couchdb2
        volumeMounts:
        - name: datacouchdbpeer0org2
          mountPath: /var/lib/couchdb
          subPath: couchdb0

      volumes:
      - name: datacouchdbpeer0org2
        persistentVolumeClaim:
          claimName: data-worker1-volumeclaim