apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: orderer0
  ports:
  - protocol: TCP
    port: 7050
    nodePort: 32556
    targetPort: 7050
  type: NodePort


---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: orderer0
spec:
  selector:
    matchLabels:
      app: orderer0
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: orderer0
    spec:
      hostAliases:
      - ip: "34.68.127.86"
        hostnames:
        - "worker2.com"

      containers:
      - image: hyperledger/fabric-orderer:1.4.0
        name: orderer0
        imagePullPolicy: Never
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric
        command: ["orderer"]
        env:

        - name: ORDERER_GENERAL_LISTENADDRESS
          value: 0.0.0.0
        - name: ORDERER_GENERAL_GENESISMETHOD
          value: file
        - name: ORDERER_GENERAL_GENESISFILE
          value: /var/hyperledger/channel/genesis.block
        - name: ORDERER_GENERAL_LOCALMSPID
          value: OrdererMSP
        - name: ORDERER_GENERAL_LOCALMSPDIR
          value: /var/hyperledger/orderer/example.com/orderers/orderer.example.com/msp
        - name: ORDERER_GENERAL_TLS_ENABLED
          value: "true"
        - name: ORDERER_GENERAL_TLS_PRIVATEKEY
          value: /var/hyperledger/orderer/example.com/orderers/orderer.example.com/tls/server.key
        - name: ORDERER_GENERAL_TLS_CERTIFICATE
          value: /var/hyperledger/orderer/example.com/orderers/orderer.example.com/tls/server.crt
        - name: CORE_PEER_TLS_SERVERHOSTOVERRIDE
          value: orderer.example.com
        - name: ORDERER_GENERAL_TLS_ROOTCAS
          value: /var/hyperledger/orderer/example.com/orderers/orderer.example.com/tls/ca.crt

        ports:
        - containerPort: 7050

        volumeMounts:
        - name: orderer-channel-artifacts
          mountPath: /var/hyperledger/channel
        - name: orderer-certificate
          mountPath: /var/hyperledger/orderer
          



      volumes:
      - name: orderer-channel-artifacts
        persistentVolumeClaim:
          claimName: data-channel-artifacts-volumeclaim
      - name: orderer-certificate
        persistentVolumeClaim:
          claimName: data-cryptoconfig-orderer-volumeclaim

  

