kind: Deployment
apiVersion: apps/v1
metadata:
  name: orderer0
spec:
  selector:
    matchLabels:
      app: orderer0
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: orderer0
    spec:

      containers:
      - image: hyperledger/fabric-orderer:1.4.0
        name: orderer0
        imagePullPolicy: Never
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric
        command: ["orderer"]
        env:
        - name: CORE_PEER_ADDRESS
          value: org2-peer0:7051
        - name: ORDERER_GENERAL_LISTENADDRESS
          value: 0.0.0.0
        - name: ORDERER_GENERAL_GENESISMETHOD
          value: file
        - name: ORDERER_GENERAL_GENESISFILE
          value: /var/hyperledger/channel/genesis.block
        - name: ORDERER_GENERAL_LOCALMSPID
          value: OrdererMSP
        - name: ORDERER_GENERAL_LOCALMSPDIR
          value: /var/hyperledger/orderer/example.com/orderers/orderer.example.com/msp
        - name: ORDERER_GENERAL_TLS_ENABLED
          value: "true"
        - name: ORDERER_GENERAL_TLS_PRIVATEKEY
          value: /var/hyperledger/orderer/example.com/orderers/orderer.example.com/tls/server.key
        - name: ORDERER_GENERAL_TLS_CERTIFICATE
          value: /var/hyperledger/orderer/example.com/orderers/orderer.example.com/tls/server.crt
        - name: ORDERER_GENERAL_TLS_ROOTCAS
          value: /var/hyperledger/orderer/example.com/orderers/orderer.example.com/tls/ca.crt

        ports:
        - containerPort: 7050

        volumeMounts:
        - name: orderer-channel-artifacts
          mountPath: /var/hyperledger/channel
        - name: orderer-certificate
          mountPath: /var/hyperledger/orderer



      volumes:
      - name: orderer-channel-artifacts
        persistentVolumeClaim:
          claimName: channel-artifacts-pv-volumeclaim
      - name: orderer-certificate
        persistentVolumeClaim:
          claimName: orderer-pv-volumeclaim

  

