kind: Deployment
apiVersion: apps/v1
metadata:
  name: org1-peer0
spec:
  selector:
    matchLabels:
      app: org1-peer0
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: org1-peer0
    spec:

      containers:
      - image: hyperledger/fabric-peer:1.4.0
        name: org1-peer0
        imagePullPolicy: Never
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: ["peer", "node", "start"]
        env:
        - name: CORE_PEER_ADDRESS
          value: org1-peer0:7051
        - name: CORE_PEER_GOSSIP_BOOTSTRAP
          value: org1-peer0:7051
        - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
          value: org1-peer0:7051
        - name: CORE_PEER_GOSSIP_ORGLEADER
          value: "false"
        - name: CORE_PEER_GOSSIP_USELEADERELECTION
          value: "true"
        - name: CORE_PEER_ID
          value: org1-peer0
        - name: CORE_PEER_LOCALMSPID
          value: Org1MSP
        - name: CORE_PEER_PROFILE_ENABLED
          value: "true"
        - name: CORE_PEER_TLS_CERT_FILE
          value: /home/org1/peers/peer0.org1.example.com/tls/server.crt
        - name: CORE_PEER_TLS_ENABLED
          value: "true"
        - name: CORE_PEER_TLS_KEY_FILE
          value: /home/org1/peers/peer0.org1.example.com/tls/server.key
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /home/org1/peers/peer0.org1.example.com/tls/ca.crt
        - name: CORE_VM_ENDPOINT
          value: unix:///host/var/run/docker.sock
        - name: FABRIC_LOGGING_SPEC
          value: DEBUG
        - name: CORE_PEER_CHAINCODELISTENADDRESS
          value: 0.0.0.0:7052
        - name: CORE_PEER_ADDRESSAUTODETECT
          value: "true"
        - name: CORE_PEER_TLS_SERVERHOSTOVERRIDE
          value: peer0.org1.example.com
        ports:
        - containerPort: 7051
        - containerPort: 7052
        - containerPort: 7053
        volumeMounts:
        - name: org1-storage
          mountPath: /home/org1

        - name: docker
          mountPath: /host/var/run/


      volumes:
      - name: org1-storage
        persistentVolumeClaim:
          claimName: peer0-pv-claim
      - name: docker
        hostPath:
          path: /var/run
          type: Directory
  

