kind: PersistentVolume
apiVersion: v1
metadata:
  name: couchdb0-peer0-org2-pv-volume
  labels:
    type: couchdb0-peer0-org2-pv-volume
    purpose: dev
spec:

  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - pankaj-worker2
  hostPath:
    path: "/home/ubuntu/coucndb-peer0-org2/"
