  
kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-worker2-volume
  labels:
    type: data-worker2-volume
    purpose: dev
spec:

  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - pankaj-worker2
  hostPath:
    path: "/home/ubuntu/data-fabric/"

---
  
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-worker2-volumeclaim
spec:
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      type: data-worker2-volume
      purpose: dev
  resources:
    requests:
      storage: 2Gi