  
kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-crypto-config-volume
  labels:
    type: data-crypto-config-volume
    purpose: dev
spec:

  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - pankaj-worker1
  hostPath:
    path: "/home/ubuntu/fabric-samples/first-network/crypto-config/"

---
  
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-crypto-config-volumeclaim
spec:
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      type: data-crypto-config-volume
      purpose: dev
  resources:
    requests:
      storage: 4Gi