kind: PersistentVolume
apiVersion: v1
metadata:
  name: orderer-pv-volume
  labels:
    type: orderer-pv-volume
    purpose: dev
spec:

  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - pankaj-worker1
  hostPath:
    path: "/home/ubuntu/fabric-samples/first-network/crypto-config/ordererOrganizations"
